// <auto-generated />
using ApiUserBank.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiUserBank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiUserBank.Models.UserBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<double>("AccountValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("UserBank");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = 12345,
                            AccountValue = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
